# Generated by Django 5.2 on 2025-04-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=500, verbose_name='ID авто')),
                ('brand', models.CharField(blank=True, max_length=500, null=True, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=500, null=True, verbose_name='Модель')),
                ('grade', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комплектация')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('fuel', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип топлива')),
                ('transmission', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип КПП')),
                ('color', models.CharField(blank=True, max_length=500, null=True, verbose_name='Цвет')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='Пробег')),
                ('photos', models.TextField(blank=True, null=True, verbose_name='Фотографии')),
            ],
        ),
    ]
